import uuid, discord, time, datetime, os
from discord.ext import commands
from functions import nbt_command_formatter
from dislash import slash_commands, Option, Type

prefix = "?"

Bot = commands.Bot(command_prefix=prefix, help_command=None)
slash = slash_commands.SlashClient(Bot)

nbt_top = '''{"Block":{"name":"minecraft:moving_block","states":{},"version":2561},"CanDestroy":["minecraft:bee_nest", "minecraft:beehive"],
"CanPlaceOn":["minecraft:sandstone","minecraft:deny","minecraft:dirt","minecraft:obsidian","minecraft:grass","minecraft:bedrock","minecraft:sand","minecraft:netherrack"],
"Count":1b,"Damage":0s,"Name":"minecraft:moving_block","WasPickedUp":0b,
"tag":{"display":{"Lore":["Generated by BedrockMechanics"],"Name":"%%name%%"},
"ench":[{"id":28s,"lvl":1s}],"movingBlock":{"name":"minecraft:Bee_nest"},
"movingEntity":{"Occupants":['''
nbt_bottom = '],"id":"Beehive"},"pistonPosX":0,"pistonPosY":0,"pistonPosZ":0}}'


class Command_nbt(commands.Cog):
    def __init__(self, Bot):
        self.Bot = Bot

    @slash.command(
        name="command_nbt",
        description="Generates an nbt for executing commands",
        options=[
            Option(
                "commands",
                "Divide your commands with '|' otherwise they will not get seperated",
                Type.STRING, True),
            Option("name", "Name of the item", Type.STRING)
        ])
    async def command_nbt(self, inter, name=None, commands=None):
        if not name: name = f"{inter.author.name}'s NBT"

        content = nbt_command_formatter(commands.replace(r'"', r'\"'))
        final_nbt = nbt_top.replace("%%name%%",
                                    name) + "\n" + content + "\n" + nbt_bottom
        final_nbt = final_nbt.replace("§", "Â§")

        g = open("nbts/nbt.txt", "w")
        g.write(final_nbt)
        g.close()

        await inter.reply("Here it is!")
        await inter.send(file=discord.File('nbts/nbt.txt'))


def setup(Bot):
    Bot.add_cog(Command_nbt(Bot))
